((title     "Mario Kart DS")
 (category  "32 Tracks")
 (attempts  0)
 (completed 0)
 (split_names ("Figure-8 Circuit" "Yoshi Falls" "Cheep Cheep Beach" "Luigi's Mansion" "Desert Hills" "Delfino Square" "Waluigi Pinball" "Shroom Ridge" "DK Pass" "Tick-Tock Clock" "Mario Circuit" "Airship Fortress" "Wario Stadium" "Peach Gardens" "Bowser Castle" "Rainbow Road" "SNES Mario Circuit 1" "N64 Moo Moo Farm" "GBA Peach Circuit" "GCN Luigi Circuit" "SNES Donut Plains 1" "N64 Frappe Snowland" "GBA Bowser Castle 2" "GCN Baby Park" "SNES Koopa Beach 2" "N64 Choco Mountain" "GBA Luigi Circuit" "GCN Mushroom Bridge" "SNES Choco Island 2" "N64 Banshee Boardwalk" "GBA Sky Garden" "GCN Yoshi Circuit"))
 (golds (
   ((title "Figure-8 Circuit"))
   ((title "Yoshi Falls"))
   ((title "Cheep Cheep Beach"))
   ((title "Luigi's Mansion"))
   ((title "Desert Hills"))
   ((title "Delfino Square"))
   ((title "Waluigi Pinball"))
   ((title "Shroom Ridge"))
   ((title "DK Pass"))
   ((title "Tick-Tock Clock"))
   ((title "Mario Circuit"))
   ((title "Airship Fortress"))
   ((title "Wario Stadium"))
   ((title "Peach Gardens"))
   ((title "Bowser Castle"))
   ((title "Rainbow Road"))
   ((title "SNES Mario Circuit 1")   (duration 1:09.621))
   ((title "N64 Moo Moo Farm")   (duration 1:40.700))
   ((title "GBA Peach Circuit")   (duration 1:26.669))
   ((title "GCN Luigi Circuit")   (duration 1:49.978))
   ((title "SNES Donut Plains 1")   (duration 1:24.435))
   ((title "N64 Frappe Snowland")   (duration 2:35.540))
   ((title "GBA Bowser Castle 2")   (duration 2:24.728))
   ((title "GCN Baby Park")   (duration 1:14.994))
   ((title "SNES Koopa Beach 2")   (duration 1:22.862))
   ((title "N64 Choco Mountain")   (duration 2:40.243))
   ((title "GBA Luigi Circuit")   (duration 2:07.499))
   ((title "GCN Mushroom Bridge")   (duration 1:45.866))
   ((title "SNES Choco Island 2")   (duration 1:31.447))
   ((title "N64 Banshee Boardwalk")   (duration 2:39.272))
   ((title "GBA Sky Garden")   (duration 2:02.961))
   ((title "GCN Yoshi Circuit")   (duration 2:15.250))))
)
