((title     "Mario Kart DS")
 (category  "Retro Tracks")
 (attempts  0)
 (completed 0)
 (split_names ("SNES Mario Circuit 1" "N64 Moo Moo Farm" "GBA Peach Circuit" "GCN Luigi Circuit" "SNES Donut Plains 1" "N64 Frappe Snowland" "GBA Bowser Castle 2" "GCN Baby Park" "SNES Koopa Beach 2" "N64 Choco Mountain" "GBA Luigi Circuit" "GCN Mushroom Bridge" "SNES Choco Island 2" "N64 Banshee Boardwalk" "GBA Sky Garden" "GCN Yoshi Circuit"))
 (golds (
   ((title "SNES Mario Circuit 1")   (duration 1:09.621))
   ((title "N64 Moo Moo Farm")   (duration 1:40.700))
   ((title "GBA Peach Circuit")   (duration 1:26.669))
   ((title "GCN Luigi Circuit")   (duration 1:49.978))
   ((title "SNES Donut Plains 1")   (duration 1:24.435))
   ((title "N64 Frappe Snowland")   (duration 2:35.540))
   ((title "GBA Bowser Castle 2")   (duration 2:24.728))
   ((title "GCN Baby Park")   (duration 1:14.994))
   ((title "SNES Koopa Beach 2")   (duration 1:22.862))
   ((title "N64 Choco Mountain")   (duration 2:40.243))
   ((title "GBA Luigi Circuit")   (duration 2:07.499))
   ((title "GCN Mushroom Bridge")   (duration 1:45.866))
   ((title "SNES Choco Island 2")   (duration 1:31.447))
   ((title "N64 Banshee Boardwalk")   (duration 2:39.272))
   ((title "GBA Sky Garden")   (duration 2:02.961))
   ((title "GCN Yoshi Circuit")   (duration 2:15.250))))
)
